# Generated by Django 4.0.4 on 2022-06-30 21:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_autor_alter_blog_subtitulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='texto',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
